/* 
 * Mixii Mobile API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MixiiPhoneUserRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MixiiPhoneUserRequestTests
    {
        // TODO uncomment below to declare an instance variable for MixiiPhoneUserRequest
        //private MixiiPhoneUserRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MixiiPhoneUserRequest
            //instance = new MixiiPhoneUserRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MixiiPhoneUserRequest
        /// </summary>
        [Test]
        public void MixiiPhoneUserRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MixiiPhoneUserRequest
            //Assert.IsInstanceOfType<MixiiPhoneUserRequest> (instance, "variable 'instance' is a MixiiPhoneUserRequest");
        }


        /// <summary>
        /// Test the property 'VerificationUuid'
        /// </summary>
        [Test]
        public void VerificationUuidTest()
        {
            // TODO unit test for the property 'VerificationUuid'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'PasswordHash'
        /// </summary>
        [Test]
        public void PasswordHashTest()
        {
            // TODO unit test for the property 'PasswordHash'
        }

    }

}
