/* 
 * Mixii Mobile API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PhoneVerificationCreationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PhoneVerificationCreationResponseTests
    {
        // TODO uncomment below to declare an instance variable for PhoneVerificationCreationResponse
        //private PhoneVerificationCreationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PhoneVerificationCreationResponse
            //instance = new PhoneVerificationCreationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PhoneVerificationCreationResponse
        /// </summary>
        [Test]
        public void PhoneVerificationCreationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PhoneVerificationCreationResponse
            //Assert.IsInstanceOfType<PhoneVerificationCreationResponse> (instance, "variable 'instance' is a PhoneVerificationCreationResponse");
        }


        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'IsCellphone'
        /// </summary>
        [Test]
        public void IsCellphoneTest()
        {
            // TODO unit test for the property 'IsCellphone'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SecondsToExpire'
        /// </summary>
        [Test]
        public void SecondsToExpireTest()
        {
            // TODO unit test for the property 'SecondsToExpire'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
