/* 
 * Mixii Mobile API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PhoneVerificationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PhoneVerificationApiTests
    {
        private PhoneVerificationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PhoneVerificationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PhoneVerificationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PhoneVerificationApi
            //Assert.IsInstanceOfType(typeof(PhoneVerificationApi), instance, "instance is a PhoneVerificationApi");
        }

        
        /// <summary>
        /// Test PhoneverificationOptions
        /// </summary>
        [Test]
        public void PhoneverificationOptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PhoneverificationOptions();
            //Assert.IsInstanceOf<SimpleResult> (response, "response is SimpleResult");
        }
        
        /// <summary>
        /// Test PhoneverificationPost
        /// </summary>
        [Test]
        public void PhoneverificationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string verificationCode = null;
            //string phoneNumber = null;
            //string authorization = null;
            //string countryCode = null;
            //var response = instance.PhoneverificationPost(verificationCode, phoneNumber, authorization, countryCode);
            //Assert.IsInstanceOf<SimpleResult> (response, "response is SimpleResult");
        }
        
        /// <summary>
        /// Test PhoneverificationPut
        /// </summary>
        [Test]
        public void PhoneverificationPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string phoneNumber = null;
            //string authorization = null;
            //string countryCode = null;
            //var response = instance.PhoneverificationPut(phoneNumber, authorization, countryCode);
            //Assert.IsInstanceOf<SimpleResult> (response, "response is SimpleResult");
        }
        
    }

}
